# docker-compose.yml
version: '3.2'
services:

  db:
    image: postgres
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_PASSWORD: s3cret
    ports:
     - 5432:5432

  # http://localhost:5080
  adminer:
    image: adminer
    container_name: admin-app
    restart: always
    environment:
     - ADMINER_DEFAULT_SERVER=db
    ports:
      - 5080:8080

  # http://localhost:9000/#/containers
  portainer:
    image: portainer/portainer
    container_name: portainer-app
    command: --no-auth
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /opt/portainer/data:/data
    ports:
     - 9000:9000

volumes:
  data:
    external: false

